defaults:
  - override job_logging: colorlog
  - override hydra_logging: colorlog

run:
  dir: ${paths.log_dir}/${task_name}/run/${now:%Y-%m-%d_%H-%M-%S}

job_logging:
  handlers:
    file:
      filename: ${hydra.runtime.output_dir}/${task_name}.log
