_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

max_epochs: 100
check_val_every_n_epoch: 1

# mixed precision for extra speed-up
precision: 16

deterministic: False
